pipeline {

    agent any

    environment {
        IMAGE_NAME = "preject-rootgit"
        IMAGE_TAG  = "${env.BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Recuperation du code...'
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('preject_rootgit') {
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                    sh "docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest"
                }
            }
        }

        stage('Syntax Check') {
            steps {
                sh "docker run --rm ${IMAGE_NAME}:${IMAGE_TAG} find /var/www/html -name '*.php' -not -path '*/vendor/*' -exec php -l {} \\;"
            }
        }

        stage('PHPUnit Tests') {
            steps {
                sh "docker run --rm ${IMAGE_NAME}:${IMAGE_TAG} bash -c 'cd /var/www/html && vendor/bin/phpunit --testdox'"
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
                    sh "docker tag ${IMAGE_NAME}:${IMAGE_TAG} $DOCKER_USER/${IMAGE_NAME}:${IMAGE_TAG}"
                    sh "docker tag ${IMAGE_NAME}:${IMAGE_TAG} $DOCKER_USER/${IMAGE_NAME}:latest"
                    sh "docker push $DOCKER_USER/${IMAGE_NAME}:${IMAGE_TAG}"
                    sh "docker push $DOCKER_USER/${IMAGE_NAME}:latest"
                    sh "docker logout"
                }
            }
        }

        stage('Terraform - Deploy') {
            steps {
                dir('preject_rootgit/terraform') {
                    sh "terraform init -input=false"
                    sh "terraform plan -var='image=chi7d/${IMAGE_NAME}:${IMAGE_TAG}' -out=tfplan"
                    sh "terraform apply -auto-approve tfplan"
                }
            }
        }

        stage('Health Check') {
            steps {
                sh "sleep 15 && kubectl get pods && kubectl get services"
            }
        }
    }

    post {
        success {
            echo 'Pipeline reussi !'
        }
        failure {
            echo 'Pipeline en echec.'
        }
        always {
            sh "docker rmi ${IMAGE_NAME}:${IMAGE_TAG} || true"
        }
    }
}